[package]
name = "tb-simplecrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "^0.8" }
rust-crypto = { version = "^0.2" }
thiserror = { version = "^1.0" }
